### ISSUE TITLE
Add a form of `ko resolve` that works with the `kubernetes_manifest` rule

### ISSUE THREAD

**Issue by mattmoor** [ko-build/terraform-provider-ko#15]
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest

**Comment by imjasonh** [comment]
I'm hoping we don't actually need to do anything to support this, but we should definitely document the use case and have working/tested examples.

AIUI you can specify a k8s manifest like:

```terraform
resource "kubernetes_manifest" "deployment" {
  manifest = {
    apiVersion = "apps/v1"
    kind       = "Deployment"
    metadata   = {
      name = "my-deployment"
    }
    spec = {
      replicas = 3
      ...
      containers = [{
        name  = "my-container"
        image = ko_image.test.image_ref
      }]
    }
  }
}
```

This lets us rely on terraform's templating instead of `ko://`-prefixing, which is nice.

The real trick will be getting terraform to output that deployment's state as YAML instead of just appying it. We might be able to use [`yamlencode`](https://www.terraform.io/language/functions/yamlencode) and an `output`.

**Comment by mattmoor** [comment]
> I'm hoping we don't actually need to do anything to support this

To clarify what I had in mind...  I was thinking of something more like:
```hcl
resource "ko_resolve" "blah" {
   recursive = true
   files = ["${path.module}/config"]
}

resource "kubernetes_manifest" "manifests" {
   for_each = ko_resolve.blah.manifests # An output from above.

   # Maybe the `ko_resolve` rule outputs something pre-decoded into HCL objects?
   manifest = yamldecode(each.value)
}
```

That way you don't need to wholly commit to terraform as "the way", but can use it as a way to connect your `ko` configs into a broader infra story.

---

Contextualizing this to something like we do in `mono`, each of our components could define a way to customize their configuration exposing knobs from a terraform module:
```hcl
variable "database-options" {}

resource "ko_resolve" "blah" {
   recursive = true
   files = ["${path.module}/config"]
}

resource "kubernetes_manifest" "manifests" {
   for_each = ko_resolve.blah.manifests # An output from above.

   # Maybe the `ko_resolve` rule outputs something pre-decoded into HCL objects?
   manifest = yamldecode(each.value)
}


resource "kubernetes_manifest" "database-config" {
   manifest = {
     apiVersion = "v1"
     kind       = "ConfigMap"
     metadata   = {
        name = "config-blah"
     }
     data = {
        driver = var.database-options.driver
        address = var.database-options.address
     }
   }
}
```

This could then be consumed multiple ways.  Here's a "dev" setup that just runs something like `mysql` on the cluster itself:
```hcl
module "devel-mysql" {
   source = "path/to/a/devel/mysql/setup"
}

module "blah" {
   source = "path/to/above"

   database-options = module.devel-mysql.options
}
```

Conversely, a more production setup might offload to a Cloud SQL instance:
```hcl
module "cloud-sql" {
   source = "path/to/cloud-sql"
}

module "blah" {
   source = "path/to/above"

   database-options = module.cloud-sql.options
}
```

---

I'm thinking that if we had a setup like this in `mono` that we could drop a LOT (or all) of our custom orchestration logic.  Folks could bootstrap a dev environment with something like:
```shell
cd env/dev
terraform init # pass some state options
terraform apply
```

... but they could still iterate on components through:
```shell
cd blah
# I'm just guessing that this is faster than doing the same through terraform,
# but that would be something to try and compare.  I'm also curious how grumpy
# terraform will be about mixing and matching.
ko apply -BRf config
```

Sorry for the delay and then switching from ultra-terse to ultra-verbose, but this is the picture that's been rattling around in my head, and I wanted to hold off until I had a moment to write it up in a way that more clearly articulated the picture in my head.

**Comment by joshrwolf** [comment]
I'm working on a doc that talks about how we move forward with CD and came to a conclusion like this without even realizing this issue existed 😅.

I'ma pick it up so we have an example to talk to when I ultimately recommend something like this for deploying our own internal stuff.

**Comment by imjasonh** [comment]
This is done now right?
